version: "3.10"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspace
      - python-packages:/usr/local/lib/python3.12/site-packages
      - python-bin:/usr/local/bin
    command: poetry install --sync

volumes:
  python-packages:
  python-bin: